{% set name = "tbparse" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tbparse-{{ version }}.tar.gz
  sha256: 528e7da6929148b612a517adb5fbdee709224cb7e2420489a9b6b174f2f808bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=1.3.0
    - tensorboard >=2.12.0

test:
  imports:
    - tbparse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/j3soon/tbparse
  summary: Load tensorboard event logs as pandas DataFrames; Read, parse, and plot tensorboard event logs with ease!
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
