{% set name = "tbparse" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tbparse-{{ version }}.tar.gz
  sha256: 3d81d903d09f9d94ac0b52f9814889c3bf5fc994f34f3d1d2b12d02bfd882ed9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - pandas >=1.3.0
    - tensorboard >=2.0.0

test:
  imports:
    - tbparse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/j3soon/tbparse
  summary: Load tensorboard event logs as pandas DataFrames; Read, parse, and plot tensorboard event logs with ease!
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
